### ISSUE TITLE
Ability for product/stemcell `version` to accept globs patterns

### ISSUE THREAD

**Issue by aegershman** [pivotalservices/file-downloader-resource#2]
I have a use case for accepting regex/glob patterns for product/stemcell versions.

I am storing my product/stemcell versions as `git` config. When a version has been applied to one environment, it writes the version to a file representing another environment. **However**, I want my `sandbox` environment to be able to take the latest `patch` version available without me having to manually update it.

This is similar to how the [`pivnet-resource` can accept a `product_version`](https://github.com/pivotal-cf/pivnet-resource#source-configuration).

**Comment by aegershman** [comment]
@calebwashburn I know you're quite busy. Nonetheless, does this seem like a feature you'd want this resource to support?

**Comment by calebwashburn** [comment]
I am thinking about having this solved a bit different.  Have a pipeline that watches pivnet using pivnet-resource or some other resource.  If there are changes have it update the file for your sandbox.  That way file-downloader always does explicit version but something upstream would be tracking lastest versions to update your config.  Not necessarily ideal but concerned about other file `drivers` not being able to translate something like `2.2.*` to a version to download.

**Comment by aegershman** [comment]
Gotcha. Okay, that was my basically plan-B if globs weren't planned to be supported first-class.

Thank you, I appreciate it. 👍

**Comment by calebwashburn** [comment]
Interested to see what you come up with in your plan-b @aegershman
